apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ratings
  description: Ratings Service
  tags:
    - java
  links:
    - url: https://devspaces.apps.cluster-l9nz6.dynamic.redhatworkshops.io/?storageType=per-workspace#https://github.com/contract-first-idp-qa/bookinfo-ratings-service
      title: OpenShift Dev Spaces
      icon: web
  annotations:
    github.com/project-slug: contract-first-idp-qa/bookinfo-ratings-service
    backstage.io/kubernetes-id: ratings
    backstage.io/kubernetes-label-selector: system=bookinfo
    janus-idp.io/tekton : ratings-service
spec:
  type: service
  lifecycle: production
  owner: group:default/backstage-admins
  system: system:default/bookinfo
  
  providesApis: 
    - ratings
  
  